### ISSUE TITLE
[BlockSparseArrays] BlockSparseArray functionality

### ISSUE THREAD

**Issue by ogauthe** [ITensor/BlockSparseArrays.jl#2]
This issue lists functionalities and feature requests for `BlockSparseArray`.

```julia
using LinearAlgebra
using NDTensors.BlockSparseArrays: BlockSparseArray

a = BlockSparseArray{Float64}([2, 3], [2, 3]);
```

# Bugs
- [ ] `LinearAlgebra.Adjoint{T,<:BlockSparseArray{T}}` returns a `BlockedArray` in certain slicing operations (https://github.com/ITensor/BlockSparseArrays.jl/issues/2).
- [ ] Fix `cat(::BlockSparseArray, ::BlockSparseArray)` for dual axes (followup to ITensor/ITensors.jl#1579).

# Feature requests
- [ ] Allow the syntax `BlockSparseArray{Float64}([U1(0) => 2, U1(1) => 3], [U1(0) => 2, U1(1) => 3])` which could implicitly create axes with `GradedUnitRange` internally.
- [ ] Use `NestedPermutedDimsArray` instead of `SparsePermutedDimsArrayBlocks` (similar to how we are removing `SparseAdjointBlocks`/`SparseTransposeBlocks` in ITensor/ITensors.jl#1580). Started in ITensor/ITensors.jl#1589, ITensor/ITensors.jl#1590.
- [ ] An alternative design to ITensor/ITensors.jl#1589 would be to redefine `NestedPermutedDimsArray` as a `PermutedDimsArray` wrapping a [`MappedArray`](https://github.com/JuliaArrays/MappedArrays.jl) where the map and inverse map convert to `PermutedDimsArray`, that would be good to explore so we don't have to support all of the `NestedPermutedDimsArrays` code, which is mostly just a copy of `Base.PermutedDimsArrays` anyway.
- [ ] If slices are just blockwise, like `b = @view a[Block.(1:2), [Block(2), Block(1)]`, define `blocks(b)` as `@view blocks(a)[1:2, [2, 1]]`, as opposed to using the more general `SparseSubArrayBlocks` in those cases. Like the new `NestedPermutedDimsArray`, in principle `SparseSubArrayBlocks` could be replaced by a `NestedSubArray` type that defines the slicing behavior of the array storing the blocks and also the slicing of the blocks themselves, but that might be overkill and the concept is very particular to block arrays. But maybe `SubArray` of the `blocks` could still be used to simplify the code logic in `SparseSubArrayBlocks`.
- [ ] Constructor from `Dictionary` should check block sizes (https://github.com/ITensor/BlockSparseArrays.jl/issues/2).
- [ ] Blockwise linear algebra operations like `svd`, `qr`, etc. See ITensor/ITensors.jl#1515. These are well defined if the block sparse matrix has a block structure (i.e. the sparsity pattern of the sparse array of arrays `blocks(a)`) corresponding to a [generalized permutation matrix](https://en.wikipedia.org/wiki/Generalized_permutation_matrix). Probably they should be called something like `block_svd`, `block_eigen`, `block_qr`, etc. to distinguish that they are meant to be used on block sparse matrices with those structures (and error if they don't have that structure). See [^linalg] for a prototype of a blockwise QR. See also [BlockDiagonals.jl](https://github.com/JuliaArrays/BlockDiagonals.jl/blob/master/src/linalg.jl) for an example in Julia of blockwise factorizations, they use a naming scheme `svd_blockwise`, `eigen_blockwise`, etc. The slicing operation introduced in ITensor/ITensors.jl#1489 will be useful for performing block-wise truncated factorizations.
- [ ] Define `Strided.@strided` for `view(::BlockSparseArray, ::Block)`. As a workaround it will work if you use `view!`/`@view!` introduced in ITensor/ITensors.jl#1498. (**EDIT:** We will have to decide what this should do, maybe it takes a strided view of the block data if the block exists, but otherwise errors if the block doesn't exist.)
- [ ] Change the behavior of slicing with non-blocked ranges (such as `a[1:2, 1:2]`) to output non-blocked arrays, and define `@blocked a[1:2, 1:2]` to explicitly preserve blocking. See the discussion in https://github.com/JuliaArrays/BlockArrays.jl/issues/347.
- [ ] Reconsider the design of how duality is stored in graded unit ranges (graded axes), for example storing it at the level of the sector labels with a new `SectorDual` type and/or as a boolean flag.
- [ ] Display non-initialized blocks differently from zero-initialized blocks, currently they both print as zeros.

# Fixed
- [x] Rename `SparseArrayInterface` to `SparseArraysBase` and move `SparseArrayDOKs` into the new `SparseArraysBase`. (Fixed in ITensor/ITensors.jl#1591, ITensor/ITensors.jl#1592.)
- [x] Constructors like `BlockSparseArray{Float64,2,Matrix{Float64}}([2, 3], [2, 3])`, `BlockSparseArray{Float64,2}([2, 3], [2, 3])`, `BlockSparseMatrix{Float64}([2, 3], [2, 3])` are not defined. (Fixed by ITensor/ITensors.jl#1586.)
- [x] Rename `block_nstored` to `block_stored_length` and `nstored` to `stored_length`. (Fixed by ITensor/ITensors.jl#1585.)
- [x] Rename `BlockSparseArrayLike` to `AnyAbstractBlockSparseArray`, which is the naming convention used in other Julia packages for a similar concept[^anygpuarray].
- [x] Implement direct sums/concatenations of block sparse arrays that preserve and make use of block sparsity. This could be done by overloading [`Base.cat`](https://docs.julialang.org/en/v1/base/arrays/#Base.cat) and related functions. (Implemented in ITensor/ITensors.jl#1579.)
- [x] Fix issues with nested slices like `@views a[[Block(2), Block(1)], [Block(2), Block(1)]][2:4, 2:4]` in Julia 1.11 (see tests marked as broken in ITensor/ITensors.jl#1539). (Fixed in ITensor/ITensors.jl#1575.)
- [x] Support for blocks that are on GPU. (Partially addressed in ITensor/ITensors.jl#1560 but more work is needed, we can track issues individually from now on.)
- [x] Better support for blocks that are not `Array`, for example `DiagonalArrays.DiagonalArray`, `SparseArrayDOKs.SparseArrayDOK`, `LinearAlgebra.Diagonal`, etc. `BlockSparseArray` can have blocks that are AbstractArray subtypes, however some operations don't preserve those types properly (i.e. implicitly convert to `Array` blocks) or don't work. (Partially addressed in ITensor/ITensors.jl#1560 but more work is needed, we can track issues individually from now on.)
- [x] [Cannot create zero dimension array](https://github.com/ITensor/BlockSparseArrays.jl/issues/2) (`BlockSparseArray{Float64}()` fails). (Fixed in ITensor/ITensors.jl#1574.)
- [x] `permutedims` crashes for some block sparse arrays (https://github.com/ITensor/BlockSparseArrays.jl/issues/2). (Fixed in ITensor/ITensors.jl#1574.)
- [x] `copy(adjoint)` [does not preserve dual axes](https://github.com/ITensor/BlockSparseArrays.jl/issues/2). (Fixed in ITensor/ITensors.jl#1574.)
- [x] `block_stored_indices(::LinearAlgebra.Adjoint{T, BlockSparseArray})` [does not transpose its indices](https://github.com/ITensor/BlockSparseArrays.jl/issues/2). (**Matt:** I don't see an issue here, the _values_ of `block_stored_indices(a')` are the nonzero/stored block locations, the `keys` of `block_stored_indices(a')` are an implementation detail and should not be used.)
- [x] `LinearAlgebra.norm(a)` [crashes](https://github.com/ITensor/BlockSparseArrays.jl/issues/2) when `a` contains `NaN`.
- [x] Slicing a `BlockSparseArray` that has `GradedUnitRange` axes (as opposed to `GradedOneTo`)  [fails](https://github.com/ITensor/BlockSparseArrays.jl/issues/2).
- [x] Sub-slices of multiple blocks [sometimes fails with a dual axis.](https://github.com/ITensor/BlockSparseArrays.jl/issues/2).
- [x] `a[:, :]` creates an array with [ill behaved axes](https://github.com/ITensor/BlockSparseArrays.jl/issues/2) (it should just be equivalent to `copy(a)`). Also triggers display error.
- [x] Printing a `BlockSparseArray` triggers `BoundsError` in some rare contexts (https://github.com/ITensor/BlockSparseArrays.jl/issues/2).
- [x] Automatically initializing a block [when only a slice is used](https://github.com/ITensor/BlockSparseArrays.jl/issues/2) (this should work if you make sure to use a view, see https://github.com/ITensor/BlockSparseArrays.jl/issues/2).
- [x] Implement slicing syntax for merging blocks, i.e. https://github.com/JuliaArrays/BlockArrays.jl/issues/359.
- [x] `a = BlockSparseArray{Float64}([2, 3], [2, 3]); @view a[Block(1, 1)]` returns a `SubArray` where the last type parameter which marks whether or not the slice supports faster linear indexing is `false`, while it should be `true` if that is the case for that block of `a` (this is addressed by ITensor/ITensors.jl#1513, `@view a[Block(1, 1)]` no longer outputs a `SubArray`, but rather either the block data directly or a `BlockView` object if the block doesn't exist yet).
- [x] `TensorAlgebra.contract` fails when called with `view(::BlockSparseArray, ::Block)` or `reshape(view(::BlockSparseArray, ::Block), ...)`. As a workaround it will work if you use `view!`/`@view!` instroduced in ITensor/ITensors.jl#1498.
- [x] Fix tests that are marked as broken in https://github.com/ITensor/ITensors.jl/blob/main/NDTensors/src/lib/BlockSparseArrays/test/test_basics.jl.
- [x] `a = BlockSparseArray{Float64}([2, 3], [2, 3]); b = @view a[Block.(1:2), Block.(1:2)]; b[Block(1, 1)] = randn(2, 2)` doesn't set the block `Block(1, 1)` (it remains uninitialized, i.e. structurally zero). I think the issue is that `@view b[Block(1, 1)]` makes two layers of `SubArray` wrappers instead of flattening down to a single layer, and those two layers are not being dispatched on properly (in general we only catch if something is a `BlockSparseArray` or a `BlockSparseArray` wrapped in a single wrapper layer).
- [x] Compatibility issues with `BlockArrays` v1.1, see CI for ITensor/ITensors.jl#1363. Fixed by ITensor/ITensors.jl#1503.
- [x] Rewrite GradedAxes using BlockArrays v1[^blockarrays_v1].
- [x] `r = gradedrange([U1(0) => 1]); a = BlockSparseArray{Float64}(r, r); size(view(a, Block(1,1))[1:1,1:1])` returns a tuple of `LabelledInteger` instead of `Int` (see discussion, keep it that way at least for now).
- [x] `r = gradedrange([U1(0) => 1]); a = BlockSparseArray{Float64}(dual(r), r); @view(a[Block(1, 1)])[1:1, 1:1]` and other combinations of `dual` lead to method ambiguity errors.
- [x] Implement slicing syntax for slicing multiple subsets of blocks, i.e. https://github.com/JuliaArrays/BlockArrays.jl/issues/358.
- [x] `dual` is not preserved when adding/subtracting `BlockSparseArray`s, i.e. `g = gradedrange([U1(0) => 1]); m = BlockSparseArray{Float64}(dual(g), g); isdual(axes(m + m, 1))` should be `true` but is `false`.
- [x] Error printing views of blocks of BlockSparseArray with GradedUnitRange axes, i.e.`r = gradedrange([U1(0) => 1]); a = BlockSparseArray{Float64}(r, r); @view a[Block(1, 1)]`.
- [x] Change the design of slicing with unit ranges, i.e. `a[2:4, 2:4]`, by using `BlockArrays.BlockSlice`.
- [x] Fix `a[Block(2), Block(2)] = randn(3, 3)`.
- [x] Fix `a[Block(2, 2)] .= 1`.
- [x] Fix `@view(a[Block(1, 1)])[1:1, 1:1] = 1`.
- [x] Throw error if `a[Block(1, 1)] = b` if `size(a[Block(1, 1)]) != size(b)`.
- [x] Fix matrix multiplication of `BlockSparseMatrix` involving dual axes.
- [x] Fix matrix multiplication involving adjointed `BlockSparseMatrix`, i.e. `a' * a` and `a * a'`, with and without dual axes.
- [x] Take the dual of the axes in `adjoint(::BlockSparseMatrix)`. Can be implemented by overloading `axes(::Adjoint{<:Any,<:AbstractBlockSparseMatrix})`.
- [x] `show(::Adjoint{<:Any,<:BlockSparseMatrix})` and  `show(::Transpose{<:Any,<:BlockSparseMatrix))` are broken.
- [x] fix `eachindex(::BlockSparseArray)` involving dual axes.
- [x] Fix [Hermitian] transposed `BlockSparseMatrix`, i.e. `a'` (in progress in[^adjoint]).
- [x] `Base.similar(a::BlockSparseArray, eltype::type)` and `Base.similar(a::BlockSparseArray, eltype::type, size::NTuple{N,AbstractUnitRange})` do not set `eltype`
- [x] Make `copy(::BlockSparseArray)` copy the blocks.
- [x] Slicing with `a[1:2, 1:2]` is not implemented yet and needs to be implemented (in progress in[^slicing]).
- [x] Function for accessing a list of initialized blocks. Currently you can use `stored_indices(blocks(a)))` to get a list of `Block` corresponding to initialized/stored blocks. Ideally there would be shorthands for this like `block_stored_indices(a)` (in progress in[^slicing]).
- [x] Function for accessing the number of initialized blocks. Currently you can use `nstored(blocks(a))` to get the number of initialized/stored blocks. Ideally there would be shorthands for this like `block_nstored(a)` (in progress in[^slicing]).
- [x] In place operations `.*=` and `./=`, such as`a .*= 2`, are broken (in progress in[^1]).
- [x] `Base.:*(::BlockSparseArray, x::Number)` and  `Base.:/(::BlockSparseArray, x::Number)`  are not defined
- [x] `Base.:*(::ComplexF64, ::BlockSparseArray{Float64})` does not change data type for empty array and crashes if `a` contains data.

[^slicing]: ITensor/ITensors.jl#1332
[^linalg]: https://github.com/ITensor/ITensors.jl/blob/v0.3.57/NDTensors/src/lib/BlockSparseArrays/src/backup/LinearAlgebraExt/qr.jl
[^adjoint]: ITensor/ITensors.jl#1470
[^blockarrays_v1]: https://github.com/ITensor/ITensors.jl/pull/1452, https://github.com/JuliaArrays/BlockArrays.jl/pull/255
[^anygpuarray]: https://github.com/JuliaGPU/GPUArrays.jl/blob/v11.1.0/lib/GPUArraysCore/src/GPUArraysCore.jl#L27, https://github.com/JuliaGPU/CUDA.jl/blob/v5.4.2/src/array.jl#L396

**Comment by ogauthe** [comment]
Issue: `setindex!(::BlockSparseArray, ::BlockIndexRange)` fails for any `AbstractGradedUnitRange`
```julia
g0 = blockedrange([2])
bsa0 = BlockSparseArray{Float64}(g0, g0)
bsa0[Block(1,1)[1:2,1:2]] = ones((2,2))  # Ok

g = gradedrange([TrivialSector=>2])
bsa = BlockSparseArray{Float64}(g, g)
bsa[Block(1,1)] = ones((2,2))  # Ok
@show bsa[Block(1,1)[1:2,1:2]]  # Ok
bsa[Block(1,1)[1:2,1:2]] = zeros((2,2))  # MethodError
```
```julia
ERROR: MethodError: no method matching LabelledNumbers.LabelledInteger{Int64, DataType}(::Int64)
The type `LabelledNumbers.LabelledInteger{Int64, DataType}` exists, but no method is defined for this combination of argument types when trying to construct it.

Closest candidates are:
  (::Type{LabelledNumbers.LabelledInteger{Value, Label}} where {Value<:Integer, Label})(::Any, ::Any)
   @ LabelledNumbers ~/.julia/packages/LabelledNumbers/Pn1xf/src/labelledinteger.jl:2
  (::Type{T})(::T) where T<:Number
   @ Core boot.jl:900
  (::Type{T})(::BigFloat) where T<:Integer
   @ Base mpfr.jl:403
  ...

Stacktrace:
 [1] convert(::Type{LabelledNumbers.LabelledInteger{Int64, DataType}}, x::Int64)
   @ Base ./number.jl:7
 [2] iterate
   @ ./range.jl:909 [inlined]
 [3] macro expansion
   @ ./cartesian.jl:66 [inlined]
 [4] _unsafe_setindex!
   @ ./multidimensional.jl:979 [inlined]
 [5] _setindex!
   @ ./multidimensional.jl:967 [inlined]
 [6] setindex!(A::BlockSparseArray{…}, v::Matrix{…}, I::BlockArrays.BlockIndexRange{…})
   @ Base ./abstractarray.jl:1413
 [7] top-level scope
   @ REPL[74]:1
Some type information was truncated. Use `show(err)` to see complete types.
```
The error is detected in `BlockSparseArrays`, however it looks pretty similar to previous issues with dual axes: the problem may be in `GradedUnitRanges`.

**Comment by mtfishman** [comment]
@ogauthe can you start a new issue? This issue list should get split into separate issues now that it is a separate repository.
